### ISSUE TITLE
[0.2.4] Autoupdater bug

### ISSUE THREAD

**Issue by mrekin** [mrekin/ScLauncher#10]
Exception in thread "main" java.lang.NullPointerException
        at ru.mrekin.sc.launcher.update.AutoUpdater.checkForUpdates(AutoUpdater.java:95)
        at ru.mrekin.sc.launcher.Launch.main(Launch.java:28)

**Comment by mrekin** [comment]
Fixed. Xml configuration return null instead expected empty string.
