### ISSUE TITLE
Bugs in 0.2.4

### ISSUE THREAD

**Issue by mrekin** [mrekin/ScLauncher#9]
1. Can't load with old svn plugin - need to catch exception
2. After first launch - actual config.xml rewrites by default settings. Need to fix.
3. Bug after first svn plugin installing
   java.lang.NullPointerException
       at ru.mrekin.sc.launcher.core.PluginManager.loadInstalledPlugins(PluginManager.java:63)
       at ru.mrekin.sc.launcher.core.PluginManager.install(PluginManager.java:249)
       at ru.mrekin.sc.launcher.gui.PluginRepoForm$1.actionPerformed(PluginRepoForm.java:67)
       at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
       at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
       at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
       at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
       at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)

**Comment by mrekin** [comment]
Bug №1 fixed. Warning exists in sout.
Bug № 3 fixed.

Bug №2 need to reproduce.
